#!/usr/bin/env python
# -*- coding:Shift-JIS -*-

# ----------------------------------------------------------------------------- #
# const                                                                         #
# ----------------------------------------------------------------------------- #

# KEY
KEY_LEFT = 1
KEY_RIGHT = 2
KEY_DOWN = 3
KEY_UP = 4
KEY_ESC = 5

# TIMER
TIMER_FALLING_SPEED = 1000

# BLOCK
TETRIMINO_SHAPE_O = 1
TETRIMINO_SHAPE_I = 2
TETRIMINO_SHAPE_T = 3
TETRIMINO_SHAPE_L = 4
TETRIMINO_SHAPE_J = 5
TETRIMINO_SHAPE_Z = 6
TETRIMINO_SHAPE_S = 7
TETRIMINO_COLOR_O = "#ffff00"
TETRIMINO_COLOR_I = "#add8e6"
TETRIMINO_COLOR_T = "#800080"
TETRIMINO_COLOR_L = "#ffa500"
TETRIMINO_COLOR_J = "#00008b"
TETRIMINO_COLOR_Z = "#008000"
TETRIMINO_COLOR_S = "#ff0000"

# DISPLAY
TITLE = "TetrisJSB"
NEXT_LABEL = "NEXT"
WINDOW_WIDTH = 450
WINDOW_HEIGHT = 550
BLOCK_SIZE = 25
TETRIS_FIELD_WIDTH = 10
TETRIS_FIELD_HEIGHT = 20
NEXT_TETRIMINO_FIELD_WIDTH = 100
NEXT_TETRIMINO_FIELD_HEIGHT = 100
BACK_GROUND_COLOR = "#bebebe"
TETRIS_BACK_GROUND_COLOR = "#ffffff"
TETRIS_OUTLINE_COLOR = "#727272"
NEXT_TETRIMINO_BACK_GROUND_COLOR = "#ffffff"
TETRIS_CANVAS_X = 25
TETRIS_CANVAS_Y = 25
NEXT_LABEL_SIZE = 12
NEXT_LABEL_X = 327
NEXT_LABEL_Y = 25
NEXT_TETRIMINO_CANVAS_X = 300
NEXT_TETRIMINO_CANVAS_Y = 50
